//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class BaseBehaviourWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(BaseBehaviour), typeof(System.Object));
		L.RegFunction("Instantiate", Instantiate);
		L.RegFunction("Destroy", Destroy);
		L.RegFunction("StartCoroutine", StartCoroutine);
		L.RegFunction("GetManager", GetManager);
		L.RegFunction("GetExtManager", GetExtManager);
		L.RegFunction("New", _CreateBaseBehaviour);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("shaderMgr", get_shaderMgr, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateBaseBehaviour(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				BaseBehaviour obj = new BaseBehaviour();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: BaseBehaviour.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instantiate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			BaseBehaviour obj = (BaseBehaviour)ToLua.CheckObject<BaseBehaviour>(L, 1);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.CheckObject<UnityEngine.Object>(L, 2);
			UnityEngine.Object o = obj.Instantiate(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Destroy(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.CheckObject<UnityEngine.Object>(L, 1);
				BaseBehaviour.Destroy(arg0);
				return 0;
			}
			else if (count == 2)
			{
				UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.CheckObject<UnityEngine.Object>(L, 1);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 2);
				BaseBehaviour.Destroy(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: BaseBehaviour.Destroy");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartCoroutine(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			BaseBehaviour obj = (BaseBehaviour)ToLua.CheckObject<BaseBehaviour>(L, 1);
			System.Collections.IEnumerator arg0 = ToLua.CheckIter(L, 2);
			UnityEngine.Coroutine o = obj.StartCoroutine(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetManager(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			Aw.Manager.BaseManager o = BaseBehaviour.GetManager(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetExtManager(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			object o = BaseBehaviour.GetExtManager(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_shaderMgr(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, BaseBehaviour.shaderMgr);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

